const predefinedGameCategories = {
    // Top 50 jeux réels populaires (février 2025, basés sur les données 2024-2025)
    "Fortnite": ["Battle Royale", "Tir", "Action"],
    "League of Legends": ["MOBA", "Stratégie", "Compétitif"],
    "VALORANT": ["FPS", "Compétitif", "Tactique"],
    "Apex Legends": ["FPS", "Battle Royale", "Action"],
    "Minecraft": ["Sandbox", "Aventure", "Survie"],
    "Counter-Strike 2": ["FPS", "Compétitif", "Action"],
    "Call of Duty: Modern Warfare/Warzone": ["FPS", "Action", "Battle Royale"],
    "Call of Duty: Warzone": ["FPS", "Battle Royale", "Action"],
    "EA Sports FC 24": ["Sport", "Football", "Simulation"],
    "Overwatch 2": ["FPS", "Héros", "Action"],
    "Elden Ring": ["Action", "RPG", "Souls-like"],
    "Genshin Impact": ["Gacha", "RPG", "Open World"],
    "The Finals": ["FPS", "Battle Royale", "Action"],
    "Vampire Survivors": ["Action", "Roguelite", "2D"],
    "Grand Theft Auto V": ["Action", "Open World", "Roleplay"],
    "Phasmophobia": ["Horreur", "Multijoueur", "Survie"],
    "World of Warcraft": ["MMORPG", "Fantaisie", "JDR"],
    "Hogwarts Legacy": ["Aventure", "Open World", "Magie"],
    "Lost Ark": ["MMORPG", "JDR", "Aventure"],
    "Final Fantasy XIV Online": ["MMORPG", "JDR", "Fantaisie"],
    "Dota 2": ["MOBA", "Stratégie", "Compétitif"],
    "Palworld": ["Survie", "Crafting", "Pokémon-like"],
    "Super Mario Bros. Wonder": ["Action", "Plateforme", "Aventure"],
    "Lethal Company": ["Action", "Roguelike", "Metroidvania"],
    "Mortal Kombat 1": ["Combat", "Action", "Gore"],
    "Just Chatting": ["IRL", "Discussion", "Communauté"],
    "Art": ["IRL", "Créatif", "Art"],
    "Sports": ["IRL", "Compétition", "Sport"],
    "Music": ["Musique", "Performance", "Live"],
    "ASMR": ["IRL", "Relaxation", "Audio"],
    "Slay the Spire": ["Stratégie", "Cartes", "Deckbuilding"],
    "Hearthstone": ["Cartes", "Stratégie", "Blizzard"],
    "Marvel Snap": ["Jeu de cartes", "Stratégie", "Marvel"],
    "Dead by Daylight": ["Survie", "Horreur", "Multijoueur"],
    "Diablo IV": ["Action", "RPG", "Hack'n'Slash"],
    "Baldur's Gate 3": ["RPG", "D&D", "Stratégie"],
    "Horizon Forbidden West": ["Action", "Aventure", "Open World"],
    "Persona 5 Royal": ["JRPG", "Tour par tour", "Social Links"],
    "Tekken 8": ["Combat", "Anime", "Compétitif"],
    "Street Fighter 6": ["Combat", "Arts martiaux", "Compétitif"],
    "Sifu": ["Combat", "Arts martiaux", "Action"],
    "Escape from Tarkov": ["Tactical", "Survie", "Simulation"],
    "XDefiant": ["FPS", "Action", "Multijoueur"],
    "Destiny 2": ["FPS", "Science-fiction", "MMO"],
    "PUBG: BATTLEGROUNDS": ["Battle Royale", "Survie", "Tir"],
    "The Outlast Trials": ["Horreur", "Survie", "Psychologique"],
    "Resident Evil 4 Remake": ["Horreur", "Survie", "Action"],
    "Alan Wake 2": ["Horreur", "Thriller", "Survie"],
    "The Binding of Isaac: Rebirth": ["Roguelike", "Action", "Indie"],
    "RimWorld": ["Stratégie", "Bac à sable", "Colonie"],
  
    // Jeux hypothétiques populaires (51-150, basés sur tendances Twitch 2025)
    "Among Us": ["Social", "Multijoueur", "Casual"],
    "Fall Guys": ["Party", "Multijoueur", "Casual"],
    "Rust": ["Survie", "Crafting", "Open World"],
    "Ark: Survival Evolved": ["Survie", "Aventure", "Dinosaures"],
    "Stardew Valley": ["Simulation", "Farming", "Aventure"],
    "Terraria": ["Sandbox", "Aventure", "Survie"],
    "Sea of Thieves": ["Pirates", "Aventure", "Multijoueur"],
    "Smite": ["MOBA", "Mythologie", "Action"],
    "Heroes of the Storm": ["MOBA", "Stratégie", "Compétitif"],
    "PUBG Mobile": ["Battle Royale", "Mobile", "Action"],
    "Warframe": ["FPS", "Science-fiction", "RPG"],
    "Monster Hunter Rise": ["Action", "RPG", "Chasse"],
    "Dark Souls III": ["Action", "RPG", "Souls-like"],
    "Sekiro: Shadows Die Twice": ["Action", "Stealth", "Souls-like"],
    "Bloodborne": ["Action", "RPG", "Horreur"],
    "Nioh 2": ["Action", "RPG", "Samouraï"],
    "Hollow Knight": ["Metroidvania", "Action", "Indie"],
    "Ori and the Blind Forest": ["Plateforme", "Aventure", "Indie"],
    "Cuphead": ["Action", "Retro", "Difficile"],
    "Hades": ["Roguelike", "Action", "Mythologie"],
    "Stumble Guys": ["Party", "Multijoueur", "Casual"],
    "Brawlhalla": ["Combat", "Plateforme", "Compétitif"],
    "Dragon Ball FighterZ": ["Combat", "Anime", "Compétitif"],
    "Guilty Gear Strive": ["Combat", "Anime", "Compétitif"],
    "Soulcalibur VI": ["Combat", "Action", "3D"],
    "FIFA 23": ["Sport", "Football", "Simulation"],
    "NBA 2K25": ["Sport", "Basketball", "Simulation"],
    "Madden NFL 25": ["Sport", "Football américain", "Simulation"],
    "iRacing": ["Simulation", "Courses", "Compétitif"],
    "Assetto Corsa": ["Simulation", "Courses", "Réaliste"],
    "Euro Truck Simulator 2": ["Simulation", "Conduite", "Relaxation"],
    "American Truck Simulator": ["Simulation", "Conduite", "Relaxation"],
    "Farming Simulator 25": ["Simulation", "Agriculture", "Relaxation"],
    "The Sims 4": ["Simulation", "Vie", "Créatif"],
    "Cities: Skylines II": ["Stratégie", "Simulation", "Gestion"],
    "Total War: Warhammer III": ["Stratégie", "Tactique", "Fantaisie"],
    "Civilization VI": ["Stratégie", "Tour par tour", "Gestion"],
    "Age of Empires IV": ["Stratégie", "Temps réel", "Historique"],
    "StarCraft II": ["Stratégie", "Temps réel", "Compétitif"],
    "Hearts of Iron IV": ["Stratégie", "Guerre", "Historique"],
    "Crusader Kings III": ["Stratégie", "Généalogie", "Rôle"],
    "Shadow of the Colossus": ["Action", "Aventure", "Open World"],
    "God of War Ragnarök": ["Action", "Aventure", "Mythologie"],
    "The Legend of Zelda: Tears of the Kingdom": ["Aventure", "Open World", "Action"],
    "Breath of the Wild": ["Aventure", "Open World", "Action"],
    "Red Dead Redemption 2": ["Action", "Open World", "Western"],
    "Cyberpunk 2077": ["Action", "RPG", "Science-fiction"],
    "The Witcher 3: Wild Hunt": ["Action", "RPG", "Fantaisie"],
    "Skyrim": ["RPG", "Open World", "Fantaisie"],
    "Dragon Age: Inquisition": ["RPG", "Fantaisie", "Stratégie"],
    "Mass Effect Legendary Edition": ["RPG", "Science-fiction", "Action"],
    "Borderlands 3": ["FPS", "RPG", "Action"],
    "DOOM Eternal": ["FPS", "Action", "Horreur"],
    "Halo Infinite": ["FPS", "Science-fiction", "Multijoueur"],
    "Titanfall 2": ["FPS", "Action", "Mechas"],
    "Rainbow Six Siege": ["FPS", "Tactique", "Compétitif"],
    "Team Fortress 2": ["FPS", "Multijoueur", "Cartoon"],
    "Left 4 Dead 2": ["FPS", "Horreur", "Coop"],
    "Payday 2": ["FPS", "Action", "Vol"],
    "Garry's Mod": ["Sandbox", "Multijoueur", "Créatif"],
    "Unturned": ["Survie", "FPS", "Open World"],
    "DayZ": ["Survie", "FPS", "Open World"],
    "7 Days to Die": ["Survie", "Zombie", "Crafting"],
    "Don't Starve Together": ["Survie", "Roguelike", "Indie"],
    "Subnautica": ["Survie", "Aventure", "Sous-marin"],
    "No Man's Sky": ["Survie", "Aventure", "Science-fiction"],
  
    // Jeux moins populaires mais joués (151-300, hypothétiques basés sur genres variés)
    "Bugsnax": ["Aventure", "Puzzle", "Indie"],
    "Celeste": ["Plateforme", "Difficile", "Indie"],
    "Hollow Knight: Silksong": ["Metroidvania", "Action", "Indie"],
    "Shovel Knight": ["Plateforme", "Action", "Retro"],
    "A Hat in Time": ["Plateforme", "Aventure", "3D"],
    "Yakuza: Like a Dragon": ["RPG", "Action", "Open World"],
    "Nier: Automata": ["Action", "RPG", "Science-fiction"],
    "Bayonetta 3": ["Action", "Hack'n'Slash", "Anime"],
    "Devil May Cry 5": ["Action", "Hack'n'Slash", "Gore"],
    "Ghost of Tsushima": ["Action", "Aventure", "Samouraï"],
    "Assassin's Creed Valhalla": ["Action", "RPG", "Open World"],
    "Far Cry 6": ["Action", "FPS", "Open World"],
    "Watch Dogs: Legion": ["Action", "Open World", "Hacking"],
    "Hitman 3": ["Stealth", "Action", "Tactique"],
    "Splatoon 3": ["FPS", "Action", "Multijoueur"],
    "Mario Kart 8 Deluxe": ["Courses", "Multijoueur", "Casual"],
    "Super Smash Bros. Ultimate": ["Combat", "Plateforme", "Compétitif"],
    "Animal Crossing: New Horizons": ["Simulation", "Vie", "Relaxation"],
    "Pokémon Scarlet/Violet": ["RPG", "Aventure", "Pokémon"],
    "Fire Emblem Engage": ["Stratégie", "Tour par tour", "Anime"],
    "Xenoblade Chronicles 3": ["JRPG", "Aventure", "Open World"],
    "Monster Hunter World": ["Action", "RPG", "Chasse"],
    "Darkest Dungeon": ["Roguelike", "Stratégie", "Horreur"],
    "Into the Breach": ["Stratégie", "Tactique", "Tour par tour"],
    "XCOM 2": ["Stratégie", "Tactique", "Science-fiction"],
    "Stellaris": ["Stratégie", "Science-fiction", "Gestion"],
    "Europa Universalis IV": ["Stratégie", "Historique", "Gestion"],
    "Victoria 3": ["Stratégie", "Économique", "Historique"],
    "Mount & Blade II: Bannerlord": ["Action", "RPG", "Stratégie"],
    "Chivalry 2": ["Action", "Multijoueur", "Médiéval"],
    "For Honor": ["Combat", "Multijoueur", "Médiéval"],
    "Gears of War 5": ["FPS", "Action", "Horreur"],
    "Battlefield 2042": ["FPS", "Action", "Multijoueur"],
    "Titanfall": ["FPS", "Action", "Mechas"],
    "The Division 2": ["FPS", "RPG", "Tactique"],
    "Ghost Recon Breakpoint": ["FPS", "Tactique", "Open World"],
    "Tom Clancy's Rainbow Six Extraction": ["FPS", "Tactique", "Horreur"],
    "Black Ops Cold War": ["FPS", "Action", "Multijoueur"],
    "Modern Warfare II": ["FPS", "Action", "Compétitif"],
    "War Thunder": ["Simulation", "Combat", "Multijoueur"],
    "World of Tanks": ["Simulation", "Combat", "Tanks"],
    "Arma 3": ["Simulation", "Tactique", "FPS"],
    "Day of Defeat: Source": ["FPS", "Tactique", "Historique"],
    "Team Fortress Classic": ["FPS", "Multijoueur", "Retro"],
    "Quake Champions": ["FPS", "Action", "Compétitif"],
    "Unreal Tournament": ["FPS", "Action", "Compétitif"],
    "Counter-Strike: Global Offensive": ["FPS", "Compétitif", "Action"],
    "Half-Life 2": ["FPS", "Action", "Science-fiction"],
    "Portal 2": ["Puzzle", "Science-fiction", "Indie"],
    "Left 4 Dead": ["FPS", "Horreur", "Coop"],
    "Payday 3": ["FPS", "Action", "Vol"],
    "GTA Online": ["Action", "Open World", "Multijoueur"],
    "Red Dead Online": ["Action", "Open World", "Western"],
    "Cyberpunk 2077 (Phantom Liberty)": ["Action", "RPG", "Science-fiction"],
    "Starfield": ["RPG", "Science-fiction", "Open World"],
    "No Man's Sky (2025 Update)": ["Survie", "Aventure", "Science-fiction"],
    "Elite Dangerous": ["Simulation", "Science-fiction", "Conduite"],
    "Kerbal Space Program": ["Simulation", "Science-fiction", "Éducation"],
    "Flight Simulator 2024": ["Simulation", "Vol", "Réaliste"],
    "Microsoft Flight Simulator": ["Simulation", "Vol", "Réaliste"],
    "Train Simulator": ["Simulation", "Conduite", "Relaxation"],
    "Bus Simulator 21": ["Simulation", "Conduite", "Relaxation"],
    "Farming Simulator 22": ["Simulation", "Agriculture", "Relaxation"],
    "City Car Driving": ["Simulation", "Conduite", "Réaliste"],
    "The Crew 2": ["Courses", "Open World", "Action"],
    "Need for Speed Unbound": ["Courses", "Action", "Open World"],
    "Gran Turismo 7": ["Courses", "Simulation", "Compétitif"],
    "Mario Party Superstars": ["Party", "Multijoueur", "Casual"],
    "Nintendo Switch Sports": ["Sport", "Multijoueur", "Casual"],
    "Wii Sports": ["Sport", "Casual", "Multijoueur"],
    "Just Dance 2025": ["Musique", "Danse", "Casual"],
    "Beat Saber": ["Musique", "VR", "Rhythm"],
    "VRChat": ["Social", "VR", "Multijoueur"],
    "Rec Room": ["Social", "VR", "Casual"],
    "GTA: San Andreas": ["Action", "Open World", "Retro"],
    "The Legend of Zelda: Breath of the Wild": ["Aventure", "Open World", "Action"],
    "Super Mario Odyssey": ["Action", "Plateforme", "Aventure"],
    "Pokémon Sword/Shield": ["RPG", "Aventure", "Pokémon"],
    "Splatoon 2": ["FPS", "Action", "Multijoueur"],
    "Fire Emblem: Three Houses": ["Stratégie", "Tour par tour", "Anime"],
    "Xenoblade Chronicles 2": ["JRPG", "Aventure", "Open World"],
    "Dragon Quest XI": ["JRPG", "Tour par tour", "Fantaisie"],
    "Final Fantasy VII Remake": ["JRPG", "Action", "Fantaisie"],
    "Persona 4 Golden": ["JRPG", "Tour par tour", "Social Links"],
    "Monster Hunter Stories 2": ["RPG", "Aventure", "Chasse"],
    "Dragon's Dogma 2": ["Action", "RPG", "Open World"],
    "Nier Replicant": ["Action", "RPG", "Science-fiction"],
    "Bayonetta": ["Action", "Hack'n'Slash", "Anime"],
    "Devil May Cry 4": ["Action", "Hack'n'Slash", "Gore"],
    "God Hand": ["Action", "Combat", "Difficile"],
    "Shadow of the Erdtree (Elden Ring DLC)": ["Action", "RPG", "Souls-like"],
    "Armored Core VI": ["Action", "Mechas", "Difficile"],
    "Metal Gear Solid V": ["Stealth", "Action", "Open World"],
    "Splinter Cell: Blacklist": ["Stealth", "Action", "Tactique"],
    "Thief (2014)": ["Stealth", "Action", "Horreur"],
    "Dishonored 2": ["Stealth", "Action", "Fantaisie"],
    "Hitman: Absolution": ["Stealth", "Action", "Tactique"],
    "Far Cry 5": ["Action", "FPS", "Open World"],
    "Watch Dogs 2": ["Action", "Open World", "Hacking"],
    "Assassin's Creed Odyssey": ["Action", "RPG", "Open World"],
    "Ghost Recon Wildlands": ["FPS", "Tactique", "Open World"],
    "Tom Clancy's The Division": ["FPS", "RPG", "Tactique"],
    "Rainbow Six Siege (2025 Update)": ["FPS", "Tactique", "Compétitif"],
    "Team Fortress 2 (2025)": ["FPS", "Multijoueur", "Cartoon"],
    "Left 4 Dead 2 (2025)": ["FPS", "Horreur", "Coop"],
    "Payday 2 (2025)": ["FPS", "Action", "Vol"],
    "Garry's Mod (2025)": ["Sandbox", "Multijoueur", "Créatif"],
    default: ["Jeux vidéo", "Divertissement"],
  };
  
  export default predefinedGameCategories;