const mockStreamers = [
  { id: "1", name: "Ninja", viewers: 18000, status: "live", country: "USA" },
  { id: "2", name: "xQc", viewers: 25000, status: "live", country: "Canada" }, // Basé au Canada mais très populaire aux US
  {
    id: "3",
    name: "Shroud",
    viewers: 14000,
    status: "live",
    country: "Canada",
  }, // Idem
  { id: "4", name: "Tfue", viewers: 6000, status: "live", country: "USA" },
  { id: "5", name: "Summit1g", viewers: 8000, status: "live", country: "USA" },
  {
    id: "6",
    name: "Sodapoppin",
    viewers: 10000,
    status: "live",
    country: "USA",
  },
  { id: "7", name: "Myth", viewers: 5000, status: "offline", country: "USA" },
  {
    id: "8",
    name: "TimTheTatman",
    viewers: 7000,
    status: "live",
    country: "USA",
  },
  { id: "9", name: "Clix", viewers: 12000, status: "live", country: "USA" },
  {
    id: "10",
    name: "Nickmercs",
    viewers: 15000,
    status: "live",
    country: "USA",
  },
  {
    id: "11",
    name: "Valkyrae",
    viewers: 8000,
    status: "offline",
    country: "USA",
  },
  { id: "12", name: "DrLupo", viewers: 6000, status: "live", country: "USA" },
  { id: "13", name: "Lirik", viewers: 9000, status: "live", country: "USA" },
  { id: "14", name: "SypherPK", viewers: 7000, status: "live", country: "USA" },
  {
    id: "15",
    name: "HasanAbi",
    viewers: 16000,
    status: "live",
    country: "USA",
  },
  {
    id: "16",
    name: "Asmongold",
    viewers: 11000,
    status: "live",
    country: "USA",
  },
  {
    id: "17",
    name: "Amouranth",
    viewers: 10000,
    status: "live",
    country: "USA",
  },
  {
    id: "18",
    name: "Fuslie",
    viewers: 4500,
    status: "offline",
    country: "USA",
  },
  {
    id: "19",
    name: "MoistCr1TiKaL",
    viewers: 8000,
    status: "live",
    country: "USA",
  },
  {
    id: "20",
    name: "CourageJD",
    viewers: 5500,
    status: "live",
    country: "USA",
  },
  { id: "21", name: "Ludwig", viewers: 12000, status: "live", country: "USA" },
  {
    id: "22",
    name: "Trainwreckstv",
    viewers: 10500,
    status: "live",
    country: "USA",
  },
  {
    id: "23",
    name: "KaiCenat",
    viewers: 30000,
    status: "live",
    country: "USA",
  },
  { id: "24", name: "Jynxzi", viewers: 20000, status: "live", country: "USA" },
  { id: "25", name: "Heelmike", viewers: 7500, status: "live", country: "USA" },
  {
    id: "26",
    name: "AdinRoss",
    viewers: 16000,
    status: "live",
    country: "USA",
  }, // Parfois sur Kick, mais inclus ici
  { id: "27", name: "Destiny", viewers: 6000, status: "live", country: "USA" },
  {
    id: "28",
    name: "Castro_1021",
    viewers: 8500,
    status: "live",
    country: "USA",
  },
  { id: "29", name: "Bugha", viewers: 7000, status: "live", country: "USA" },
  {
    id: "30",
    name: "TinaKitten",
    viewers: 5000,
    status: "offline",
    country: "USA",
  },
  { id: "31", name: "Sykkuno", viewers: 7000, status: "live", country: "USA" },
  { id: "32", name: "Scump", viewers: 9000, status: "live", country: "USA" },
  { id: "33", name: "Swagg", viewers: 8500, status: "live", country: "USA" },
  { id: "34", name: "Nadeshot", viewers: 6000, status: "live", country: "USA" },
  {
    id: "35",
    name: "LosPollosTV",
    viewers: 5500,
    status: "live",
    country: "USA",
  },
  {
    id: "36",
    name: "Pokimane",
    viewers: 9000,
    status: "offline",
    country: "Canada",
  }, // Basée aux US souvent
  {
    id: "37",
    name: "DrDisrespect",
    viewers: 0,
    status: "offline",
    country: "USA",
  }, // Banni, mais notoire
  { id: "38", name: "Zombs", viewers: 4000, status: "live", country: "USA" },
  { id: "39", name: "Aceu", viewers: 6500, status: "live", country: "USA" },
  {
    id: "40",
    name: "ImperialHal",
    viewers: 8000,
    status: "live",
    country: "USA",
  },
  { id: "41", name: "Hiko", viewers: 4500, status: "live", country: "USA" },
  {
    id: "42",
    name: "NICKMERCS",
    viewers: 13000,
    status: "live",
    country: "USA",
  }, // Variante orthographique
  {
    id: "43",
    name: "QuarterJade",
    viewers: 4000,
    status: "offline",
    country: "USA",
  },
  {
    id: "44",
    name: " shroud",
    viewers: 14000,
    status: "live",
    country: "Canada",
  }, // Doublon corrigé
  {
    id: "45",
    name: "FaZe_Swagg",
    viewers: 7000,
    status: "live",
    country: "USA",
  },
  {
    id: "46",
    name: "TypicalGamer",
    viewers: 6000,
    status: "live",
    country: "Canada",
  }, // Basé aux US
  {
    id: "47",
    name: "NinjaHyper",
    viewers: 5000,
    status: "live",
    country: "USA",
  },
  {
    id: "48",
    name: " shroudTV",
    viewers: 12000,
    status: "live",
    country: "Canada",
  }, // Variante
  {
    id: "49",
    name: "TSM_ImperialHal",
    viewers: 8500,
    status: "live",
    country: "USA",
  },
  {
    id: "50",
    name: "CohhCarnage",
    viewers: 5500,
    status: "live",
    country: "USA",
  },

  {
    id: "1",
    name: "Squeezie",
    viewers: 15000,
    status: "live",
    country: "France",
  },
  {
    id: "2",
    name: "Gotaga",
    viewers: 12000,
    status: "live",
    country: "France",
  },
  {
    id: "3",
    name: "Kameto",
    viewers: 14000,
    status: "live",
    country: "France",
  },
  {
    id: "4",
    name: "Aminematue",
    viewers: 13000,
    status: "live",
    country: "France",
  },
  {
    id: "5",
    name: "Domingo",
    viewers: 9000,
    status: "live",
    country: "France",
  },
  {
    id: "6",
    name: "ZeratoR",
    viewers: 10000,
    status: "live",
    country: "France",
  },
  {
    id: "7",
    name: "Sardoche",
    viewers: 8000,
    status: "live",
    country: "France",
  },
  {
    id: "8",
    name: "Locklear",
    viewers: 7000,
    status: "live",
    country: "France",
  },
  {
    id: "9",
    name: "Etoiles",
    viewers: 6000,
    status: "live",
    country: "France",
  },
  {
    id: "10",
    name: "BillyRebeuDeter",
    viewers: 8500,
    status: "live",
    country: "France",
  },
  {
    id: "11",
    name: "Michou",
    viewers: 11000,
    status: "live",
    country: "France",
  },
  {
    id: "12",
    name: "Inoxtag",
    viewers: 9500,
    status: "live",
    country: "France",
  },
  {
    id: "13",
    name: "LeBouseuh",
    viewers: 6500,
    status: "live",
    country: "France",
  },
  {
    id: "14",
    name: "Tonton",
    viewers: 5000,
    status: "live",
    country: "France",
  }, // Basé en Suisse mais francophone
  {
    id: "15",
    name: "JLTomy",
    viewers: 7000,
    status: "live",
    country: "France",
  },
  { id: "16", name: "Ponce", viewers: 6000, status: "live", country: "France" },
  {
    id: "17",
    name: "Solary",
    viewers: 8000,
    status: "live",
    country: "France",
  }, // Chaîne collective
  {
    id: "18",
    name: "Shaunz",
    viewers: 5500,
    status: "live",
    country: "France",
  },
  {
    id: "19",
    name: "Doigby",
    viewers: 6000,
    status: "live",
    country: "France",
  },
  { id: "20", name: "Tiky", viewers: 7000, status: "live", country: "France" },
  { id: "21", name: "Nisqy", viewers: 5000, status: "live", country: "France" },
  {
    id: "22",
    name: "Shisheyu",
    viewers: 4500,
    status: "live",
    country: "France",
  },
  {
    id: "23",
    name: "MasterSnakou",
    viewers: 4000,
    status: "live",
    country: "France",
  },
  { id: "24", name: "Pfut", viewers: 5000, status: "live", country: "France" },
  {
    id: "25",
    name: "JeanMassiet",
    viewers: 6000,
    status: "live",
    country: "France",
  },
  {
    id: "26",
    name: "SamuelEtienne",
    viewers: 7000,
    status: "live",
    country: "France",
  },
  {
    id: "27",
    name: "Brawks",
    viewers: 4500,
    status: "live",
    country: "France",
  },
  {
    id: "28",
    name: "MisterMV",
    viewers: 4000,
    status: "live",
    country: "France",
  },
  {
    id: "29",
    name: "Trinity",
    viewers: 3500,
    status: "live",
    country: "France",
  },
  { id: "30", name: "Kotei", viewers: 5000, status: "live", country: "France" },
  {
    id: "31",
    name: "LeStream",
    viewers: 6000,
    status: "offline",
    country: "France",
  }, // Ancienne WebTV
  {
    id: "32",
    name: "Alderiate",
    viewers: 4000,
    status: "live",
    country: "France",
  },
  {
    id: "33",
    name: "Skyrroz",
    viewers: 4500,
    status: "live",
    country: "France",
  },
  { id: "34", name: "Un33d", viewers: 5000, status: "live", country: "France" },
  {
    id: "35",
    name: "Valouzz",
    viewers: 6000,
    status: "live",
    country: "France",
  },
  {
    id: "36",
    name: "Baghera",
    viewers: 4000,
    status: "live",
    country: "France",
  },
  {
    id: "37",
    name: "Hortyy",
    viewers: 3500,
    status: "live",
    country: "France",
  },
  { id: "38", name: "Lutti", viewers: 4500, status: "live", country: "France" },
  { id: "39", name: "Kamel", viewers: 4000, status: "live", country: "France" },
  {
    id: "40",
    name: "Skyyart",
    viewers: 5000,
    status: "live",
    country: "France",
  },
  {
    id: "41",
    name: "Chowh1",
    viewers: 4500,
    status: "live",
    country: "France",
  },
  {
    id: "42",
    name: "Wankil",
    viewers: 6000,
    status: "live",
    country: "France",
  },
  { id: "43", name: "MoMaN", viewers: 4000, status: "live", country: "France" },
  {
    id: "44",
    name: "Lecrivaindujour",
    viewers: 3500,
    status: "live",
    country: "France",
  },
  {
    id: "45",
    name: "KevAdams",
    viewers: 5000,
    status: "offline",
    country: "France",
  },
  {
    id: "46",
    name: "RebeuDeter",
    viewers: 7000,
    status: "live",
    country: "France",
  }, // Variante Billy
  {
    id: "47",
    name: "AntoineDaniel",
    viewers: 4500,
    status: "live",
    country: "France",
  },
  {
    id: "48",
    name: "Jiraya",
    viewers: 4000,
    status: "live",
    country: "France",
  },
  {
    id: "49",
    name: "MisterV",
    viewers: 5500,
    status: "live",
    country: "France",
  },
  {
    id: "50",
    name: "ZackNani",
    viewers: 5000,
    status: "live",
    country: "France",
  },
];

export default mockStreamers;